# Generated by Django 6.0.2 on 2026-03-17 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorat', '0003_alter_disponibilite_options_alter_evaluation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('individuel', 'Individuel'), ('groupe', 'Groupe'), ('support', 'Support')], default='individuel', max_length=20)),
                ('dernier_message', models.DateTimeField(blank=True, null=True)),
                ('nombre_messages', models.PositiveIntegerField(default=0)),
                ('nombre_non_lus', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_creees', to=settings.AUTH_USER_MODEL)),
                ('groupe_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tutorat.groupetutorat')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'communication_conversation',
                'ordering': ['-dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('informatique', 'Informatique'), ('français', 'Français'), ('anglais', 'Anglais'), ('histoire', 'Histoire'), ('geographie', 'Géographie'), ('economie', 'Économie'), ('autre', 'Autre')], max_length=50)),
                ('matiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('fichiers', models.JSONField(blank=True, default=list)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('nombre_reponses', models.PositiveIntegerField(default=0)),
                ('resolu', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question forum',
                'verbose_name_plural': 'Questions forum',
                'db_table': 'communication_forum_question',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ForumReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichiers', models.JSONField(blank=True, default=list)),
                ('votes_positifs', models.PositiveIntegerField(default=0)),
                ('votes_negatifs', models.PositiveIntegerField(default=0)),
                ('voteurs', models.JSONField(blank=True, default=dict)),
                ('est_meilleure_reponse', models.BooleanField(default=False)),
                ('date_meilleure_reponse', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='communication.forumquestion')),
            ],
            options={
                'verbose_name': 'Réponse forum',
                'verbose_name_plural': 'Réponses forum',
                'db_table': 'communication_forum_reponse',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='meilleure_reponse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_resolue', to='communication.forumreponse'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier'), ('image', 'Image'), ('lien', 'Lien'), ('systeme', 'Message système')], default='texte', max_length=20)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('lu_par', models.JSONField(blank=True, default=list)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('supprime_par', models.JSONField(blank=True, default=list)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='communication.message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'communication_message',
                'ordering': ['date_envoi'],
            },
        ),
    ]
