# Generated by Django 6.0.2 on 2026-03-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('demande_seance', 'Demande de séance'), ('acceptation_seance', 'Acceptation de séance'), ('annulation_seance', 'Annulation de séance'), ('message_recu', 'Message reçu'), ('reponse_forum', 'Réponse sur le forum'), ('validation_ressource', 'Validation de ressource'), ('inscription_groupe', 'Inscription à un groupe'), ('acceptation_groupe', 'Acceptation dans un groupe'), ('rappel_seance', 'Rappel de séance'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('lien', models.CharField(blank=True, help_text='Lien vers la ressource concernée (URL relative ou absolue)', max_length=500)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
