# Generated by Django 6.0.2 on 2026-03-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('matiere', models.CharField(blank=True, max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('lien', 'Lien'), ('image', 'Image')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('lien_externe', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('signale', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ressources.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('ressource', 'Ressource'), ('commentaire', 'Commentaire')], max_length=20)),
                ('id_contenu', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('signalant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersionRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='ressources/versions/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ressources.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='NoteRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ressources.ressource')),
            ],
            options={
                'unique_together': {('ressource', 'auteur')},
            },
        ),
        migrations.CreateModel(
            name='FavoriRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource')),
            ],
            options={
                'unique_together': {('utilisateur', 'ressource')},
            },
        ),
    ]
