# Generated by Django 6.0.2 on 2026-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='matiere',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='niveau',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('rejete', 'Rejeté')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
