# Generated by Django 6.0.2 on 2026-03-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_alter_ressource_date_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='type_fichier',
            field=models.CharField(choices=[('cours', 'Cours'), ('pdf', 'PDF'), ('exercice', 'Exercice'), ('corrige', 'Corrigé'), ('video', 'Vidéo'), ('lien', 'Lien'), ('image', 'Image')], max_length=20),
        ),
    ]
