# Generated by Django 6.0.2 on 2026-04-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_alter_ressource_type_fichier'),
        ('tutorat', '0008_delete_inscriptionseance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorat.ressource'),
        ),
        migrations.AlterField(
            model_name='commentaireressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='tutorat.ressource'),
        ),
        migrations.AlterField(
            model_name='noteressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ressources', to='tutorat.ressource'),
        ),
        migrations.AlterField(
            model_name='versionressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tutorat.ressource'),
        ),
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
