# Generated by Django 6.0.2 on 2026-04-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_alter_favoriressource_ressource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('matiere', models.CharField(blank=True, db_index=True, max_length=100)),
                ('niveau', models.CharField(blank=True, db_index=True, max_length=50)),
                ('type_fichier', models.CharField(choices=[('cours', 'Cours'), ('pdf', 'PDF'), ('exercice', 'Exercice'), ('corrige', 'Corrigé'), ('video', 'Vidéo'), ('lien', 'Lien'), ('image', 'Image')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('lien_externe', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('rejete', 'Rejeté')], db_index=True, default='en_attente', max_length=20)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('date_publication', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_globales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ressource globale',
                'verbose_name_plural': 'Ressources globales',
                'db_table': 'ressources_globales',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.AlterField(
            model_name='commentaireressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ressources.ressource'),
        ),
        migrations.AlterField(
            model_name='favoriressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource'),
        ),
        migrations.AlterField(
            model_name='noteressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ressources.ressource'),
        ),
        migrations.AlterField(
            model_name='versionressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ressources.ressource'),
        ),
    ]
