# Generated by Django 6.0.2 on 2026-05-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0005_ressource_alter_commentaireressource_ressource_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ressource',
            table='ressources_globales',
        ),
        migrations.AlterModelOptions(
            name='ressource',
            options={'verbose_name': 'Ressource globale', 'verbose_name_plural': 'Ressources globales', 'ordering': ['-date_publication']},
        ),
        migrations.AlterField(
            model_name='ressource',
            name='matiere',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='niveau',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('rejete', 'Rejeté')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='auteur',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='ressources_globales', to='accounts.user'),
        ),
    ]
