# Generated by Django 6.0.2 on 2026-05-02 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0008_fix_table_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartageRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, help_text='Message personnel pour le destinataire')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_recues', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_envoyees', to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='ressources.ressource')),
            ],
            options={
                'verbose_name': 'Partage de ressource',
                'verbose_name_plural': 'Partages de ressources',
                'db_table': 'ressources_partagees',
                'ordering': ['-date_partage'],
                'unique_together': {('ressource', 'destinataire')},
            },
        ),
    ]
