# Generated by Django 6.0.2 on 2026-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0009_partageressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='commentaire_rejet',
            field=models.TextField(blank=True, help_text='Motif du rejet de la ressource', null=True),
        ),
    ]
