# Generated by Django 6.0.2 on 2026-05-26 11:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0010_ressource_commentaire_rejet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resource'),
        ),
        migrations.AlterField(
            model_name='versionressource',
            name='fichier',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resource'),
        ),
    ]
