# Generated by Django 6.0.2 on 2026-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0010_ressource_commentaire_rejet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='fichier',
            field=models.URLField(blank=True, help_text='URL Cloudinary du fichier', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='versionressource',
            name='fichier',
            field=models.URLField(blank=True, help_text='URL Cloudinary de la version', max_length=500, null=True),
        ),
    ]
