# Generated by Django 6.0.2 on 2026-03-28 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeTutorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('matiere', models.CharField(blank=True, max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_tutorat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='FichierGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='fichiers_groupe/')),
                ('type_fichier', models.CharField(max_length=50)),
                ('taille', models.PositiveIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_partages', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='messaging.groupetutorat')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('enonce', models.TextField()),
                ('correction', models.TextField(blank=True)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_crees', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='messaging.groupetutorat')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier'), ('exercice', 'Exercice'), ('correction', 'Correction')], default='texte', max_length=20)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='fichiers_groupe/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
                ('est_supprime', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.groupetutorat')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='SessionTutorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=60)),
                ('lien_visio', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifie', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='messaging.groupetutorat')),
                ('participants', models.ManyToManyField(related_name='sessions_participees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_membre', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='messaging.groupetutorat')),
            ],
            options={
                'unique_together': {('groupe', 'etudiant')},
            },
        ),
    ]
