# Generated by Django 6.0.2 on 2026-04-08 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('tutorat', '0008_delete_inscriptionseance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontutorat',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutorat.groupetutorat'),
        ),
        migrations.AlterField(
            model_name='messagegroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_messaging', to='tutorat.groupetutorat'),
        ),
        migrations.AlterField(
            model_name='membregroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_messaging', to='tutorat.groupetutorat'),
        ),
        migrations.AlterField(
            model_name='fichiergroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='tutorat.groupetutorat'),
        ),
        migrations.AlterField(
            model_name='exercicegroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='tutorat.groupetutorat'),
        ),
        migrations.AlterField(
            model_name='membregroupe',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_membre_messaging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagegroupe',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe_messaging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupeTutorat',
        ),
    ]
