# Generated by Django 6.0.2 on 2026-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('tuteur', 'Tuteur'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], default='etudiant', max_length=20)),
                ('filiere', models.CharField(blank=True, max_length=100, null=True)),
                ('annee', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('centres_interet', models.TextField(blank=True, help_text='Pour les étudiants')),
                ('matières_maitrisées', models.TextField(blank=True, help_text='Pour les tuteurs')),
                ('tarif_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
