# Generated by Django 6.0.2 on 2026-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_matières_maitrisées_user_matieres_maitrisees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
