# Generated by Django 6.0.2 on 2026-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_suspended_user_suspension_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='annee',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('tuteur', 'Tuteur'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], db_index=True, default='etudiant', max_length=20),
        ),
    ]
