# Generated by Django 6.0.2 on 2026-03-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_annee_alter_user_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='biographie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date_certification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='matieres_enseignees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_enseignement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_etudes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_evaluations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='note_moyenne',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='objectifs_apprentissage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences_apprentissage', models.JSONField(blank=True, default=list)),
                ('difficultes', models.JSONField(blank=True, default=list)),
                ('objectifs_specifiques', models.TextField(blank=True)),
                ('disponibilites_etudiant', models.JSONField(blank=True, default=list)),
                ('budget_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferences_horaires', models.JSONField(blank=True, default=dict)),
                ('sessions_suivies', models.PositiveIntegerField(default=0)),
                ('temps_apprentissage', models.DurationField(blank=True, null=True)),
                ('matieres_etudiees', models.JSONField(blank=True, default=list)),
                ('progression_globale', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomes', models.JSONField(blank=True, default=list)),
                ('competences', models.JSONField(blank=True, default=list)),
                ('langues', models.JSONField(blank=True, default=list)),
                ('methodes_enseignement', models.TextField(blank=True)),
                ('disponibilites_speciales', models.TextField(blank=True)),
                ('zone_geographique', models.CharField(blank=True, max_length=200)),
                ('accepte_en_ligne', models.BooleanField(default=True)),
                ('accepte_presentiel', models.BooleanField(default=False)),
                ('tarif_reduit', models.BooleanField(default=False)),
                ('conditions_reductions', models.TextField(blank=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_etudiants', models.PositiveIntegerField(default=0)),
                ('taux_reponse', models.FloatField(default=0.0)),
                ('taux_completion', models.FloatField(default=0.0)),
                ('temps_moyen_reponse', models.DurationField(blank=True, null=True)),
                ('performance_matieres', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
