# Generated by Django 6.0.2 on 2026-03-18 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_user_badges_user_biographie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('push_notifications', models.BooleanField(default=False, verbose_name='Notifications push')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Sauvegarde automatique')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Autoriser les inscriptions')),
                ('require_email_verification', models.BooleanField(default=True, verbose_name='Vérification email requise')),
                ('max_file_size', models.PositiveIntegerField(default=10, help_text='Taille max des fichiers en MB')),
                ('max_users_per_day', models.PositiveIntegerField(default=100, help_text="Nombre max d'inscriptions par jour")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
    ]
