# Generated by Django 6.0.2 on 2026-03-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_tutor_badges'),
        ('accounts', '0006_systemsettings'),
    ]

    operations = [
    ]
