# Generated by Django 6.0.2 on 2026-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0003_add_tutor_badges_0006_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, help_text='URL Cloudinary de la photo de profil', max_length=500, null=True),
        ),
    ]
