# Generated by Django 6.0.2 on 2026-05-23 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_conversation', models.CharField(choices=[('individuelle', 'Individuelle (1-à-1)'), ('groupe_etudiants', 'Groupe étudiants'), ('groupe_tuteurs', 'Groupe tuteurs'), ('support_admin', 'Support administratif'), ('tutorat_groupe', 'Groupe tutorat')], default='individuelle', max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée'), ('suspendue', 'Suspendue')], default='active', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='conversation_avatars/')),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_message', models.DateTimeField(blank=True, null=True)),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
                ('autoriser_fichiers', models.BooleanField(default=True)),
                ('taille_max_fichier', models.IntegerField(default=52428800)),
                ('nb_max_participants', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('echec', 'Échec'), ('recu', 'Reçu'), ('lu', 'Lu'), ('repondu', 'Répondu')], default='envoye', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('email_id_externe', models.CharField(blank=True, max_length=100)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messagerie_email_message',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='AccuseReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_accus', models.CharField(choices=[('envoi', 'Confirmation envoi'), ('reception', 'Confirmation réception'), ('lecture', 'Confirmation lecture')], max_length=20)),
                ('date_accus', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuses', to='messagerie.emailmessage')),
            ],
            options={
                'db_table': 'messagerie_accuse_reception',
                'ordering': ['-date_accus'],
            },
        ),
        migrations.CreateModel(
            name='EmailReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='messagerie.emailmessage')),
            ],
            options={
                'db_table': 'messagerie_email_reponse',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Vidéo'), ('lien_ressource', 'Lien ressource'), ('invitation_seance', 'Invitation séance'), ('systeme', 'Message système')], default='texte', max_length=20)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages_fichiers/%Y/%m/')),
                ('nom_original_fichier', models.CharField(blank=True, max_length=255)),
                ('type_fichier', models.CharField(blank=True, max_length=50)),
                ('taille_fichier', models.IntegerField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('est_edite', models.BooleanField(default=False)),
                ('est_supprime', models.BooleanField(default=False)),
                ('est_forward', models.BooleanField(default=False)),
                ('nb_reactions', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagerie_messages', to='messagerie.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagerie_messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('message_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='messagerie.message')),
                ('message_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='messagerie.message')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantsConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('participant', 'Participant'), ('observateur', 'Observateur')], default='participant', max_length=20)),
                ('a_rejoint', models.DateTimeField(auto_now_add=True)),
                ('a_quitte', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('peut_ecrire', models.BooleanField(default=True)),
                ('peut_partager_fichiers', models.BooleanField(default=True)),
                ('peut_inviter', models.BooleanField(default=False)),
                ('notifications_activees', models.BooleanField(default=True)),
                ('dernier_message_lu', models.DateTimeField(blank=True, null=True)),
                ('nb_messages_non_lus', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_details', to='messagerie.conversation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_participees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['conversation__date_creation', 'a_rejoint'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='messagerie_conversations', through='messagerie.ParticipantsConversation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PieceJointeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='messages_pieces_jointes/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=50)),
                ('taille', models.IntegerField()),
                ('vignette', models.ImageField(blank=True, null=True, upload_to='vignettes/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_virus_scanne', models.BooleanField(default=False)),
                ('est_chiffre', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='messagerie.message')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='ReactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reaction', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠'), ('custom', 'Custom')], max_length=20)),
                ('emoji_custom', models.CharField(blank=True, max_length=10)),
                ('date_reaction', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messagerie.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reaction'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['expediteur', 'statut'], name='messagerie__expedit_69cdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['destinataire', 'statut'], name='messagerie__destina_1afc03_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['date_envoi'], name='messagerie__date_en_c11f45_idx'),
        ),
        migrations.AddIndex(
            model_name='accusereception',
            index=models.Index(fields=['email', 'type_accus'], name='messagerie__email_i_34d68d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreponse',
            index=models.Index(fields=['email_original', 'date_envoi'], name='messagerie__email_o_a67a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'date_envoi'], name='messagerie__convers_7584d1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='messagerie__expedit_f7b308_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantsconversation',
            unique_together={('conversation', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='reactionmessage',
            unique_together={('message', 'utilisateur', 'type_reaction')},
        ),
    ]
