# Generated by Django 6.0.2 on 2026-03-14 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('lu', 'Lu'), ('repondu', 'Répondu')], default='envoye', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('email_id_externe', models.CharField(blank=True, max_length=100)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messagerie_email_message',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='AccuseReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_accus', models.CharField(choices=[('envoi', 'Confirmation envoi'), ('reception', 'Confirmation réception'), ('lecture', 'Confirmation lecture')], max_length=20)),
                ('date_accus', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuses', to='messagerie.emailmessage')),
            ],
            options={
                'db_table': 'messagerie_accuse_reception',
                'ordering': ['-date_accus'],
            },
        ),
        migrations.CreateModel(
            name='EmailReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='messagerie.emailmessage')),
            ],
            options={
                'db_table': 'messagerie_email_reponse',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['expediteur', 'statut'], name='messagerie__expedit_69cdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['destinataire', 'statut'], name='messagerie__destina_1afc03_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['date_envoi'], name='messagerie__date_en_c11f45_idx'),
        ),
        migrations.AddIndex(
            model_name='accusereception',
            index=models.Index(fields=['email', 'type_accus'], name='messagerie__email_i_34d68d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreponse',
            index=models.Index(fields=['email_original', 'date_envoi'], name='messagerie__email_o_a67a9b_idx'),
        ),
    ]
