# Generated by Django 6.0.2 on 2026-03-27 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0003_alter_conversation_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantsConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('participant', 'Participant'), ('observateur', 'Observateur')], default='participant', max_length=20)),
                ('a_rejoint', models.DateTimeField(auto_now_add=True)),
                ('a_quitte', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('peut_ecrire', models.BooleanField(default=True)),
                ('peut_partager_fichiers', models.BooleanField(default=True)),
                ('peut_inviter', models.BooleanField(default=False)),
                ('notifications_activees', models.BooleanField(default=True)),
                ('dernier_message_lu', models.DateTimeField(blank=True, null=True)),
                ('nb_messages_non_lus', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['conversation__date_creation', 'a_rejoint'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='messages_pieces_jointes/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=50)),
                ('taille', models.IntegerField()),
                ('vignette', models.ImageField(blank=True, null=True, upload_to='vignettes/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_virus_scanne', models.BooleanField(default=False)),
                ('est_chiffre', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='ReactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reaction', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠'), ('custom', 'Custom')], max_length=20)),
                ('emoji_custom', models.CharField(blank=True, max_length=10)),
                ('date_reaction', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_reaction'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='autoriser_fichiers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_avatars/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='nb_max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée'), ('suspendue', 'Suspendue')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='taille_max_fichier',
            field=models.IntegerField(default=52428800),
        ),
        migrations.AddField(
            model_name='conversation',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='type_conversation',
            field=models.CharField(choices=[('individuelle', 'Individuelle (1-à-1)'), ('groupe_etudiants', 'Groupe étudiants'), ('groupe_tuteurs', 'Groupe tuteurs'), ('support_admin', 'Support administratif'), ('tutorat_groupe', 'Groupe tutorat')], default='individuelle', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='est_edite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='est_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messages_fichiers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='messagerie.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='messagerie.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='nb_reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='nom_original_fichier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='taille_fichier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type_fichier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Vidéo'), ('lien_ressource', 'Lien ressource'), ('invitation_seance', 'Invitation séance'), ('systeme', 'Message système')], default='texte', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'date_envoi'], name='messagerie__convers_7584d1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='messagerie__expedit_f7b308_idx'),
        ),
        migrations.AddField(
            model_name='participantsconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_details', to='messagerie.conversation'),
        ),
        migrations.AddField(
            model_name='participantsconversation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_participees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='messagerie_conversations', through='messagerie.ParticipantsConversation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piecejointemessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='messagerie.message'),
        ),
        migrations.AddField(
            model_name='reactionmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messagerie.message'),
        ),
        migrations.AddField(
            model_name='reactionmessage',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participantsconversation',
            unique_together={('conversation', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='reactionmessage',
            unique_together={('message', 'utilisateur', 'type_reaction')},
        ),
    ]
