# Generated by Django 6.0.2 on 2026-03-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('matiere', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500)),
                ('est_resolue', models.BooleanField(default=False)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_reponse', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_solution', models.BooleanField(default=False)),
                ('nb_votes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.question')),
            ],
            options={
                'ordering': ['-est_solution', '-nb_votes', 'date'],
            },
        ),
        migrations.CreateModel(
            name='VoteReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.SmallIntegerField(choices=[(1, 'Pour'), (-1, 'Contre')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.reponse')),
                ('votant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reponse', 'votant')},
            },
        ),
    ]
