# Generated by Django 6.0.2 on 2026-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_question_deleted_reponse_deleted_moderationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='matiere',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
