# Generated by Django 6.0.2 on 2026-04-10 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_add_priorite_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='priorite',
            field=models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], db_index=True, default='moyenne', max_length=10),
        ),
        migrations.CreateModel(
            name='MessageVocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_audio', models.FileField(upload_to='messages_vocaux/%Y/%m/')),
                ('duree', models.DurationField(help_text='Durée du message vocal')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_vocaux_forum', to=settings.AUTH_USER_MODEL)),
                ('reponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_vocaux', to='forum.reponse')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='forum.question')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_abonnement'],
                'unique_together': {('question', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='NotificationForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouvelle_reponse', 'Nouvelle réponse'), ('solution', 'Solution acceptée'), ('vocal', 'Message vocal'), ('mention', 'Mention'), ('abonnement', 'Nouveau message sur question suivie')], max_length=30)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_forum', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_forum', to='forum.question')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='forum_notif_destina_e230f1_idx'), models.Index(fields=['date_creation'], name='forum_notif_date_cr_49a93f_idx')],
            },
        ),
    ]
