# Generated by Django 6.0.2 on 2026-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_question_priorite_messagevocal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevocal',
            name='fichier_audio',
            field=models.FileField(help_text='Fichier audio (.3gp, .m4a, .mp3, .wav)', upload_to='messages_vocaux/%Y/%m/'),
        ),
    ]
