# Generated by Django 6.0.2 on 2026-03-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Jour 0'), (1, 'Jour 1'), (2, 'Jour 2'), (3, 'Jour 3'), (4, 'Jour 4'), (5, 'Jour 5'), (6, 'Jour 6')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_recurrent', models.BooleanField(default=True)),
                ('tuteur', models.ForeignKey(limit_choices_to={'role__in': ['tuteur', 'enseignant']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreTutorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('matiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('individuel', 'Individuel'), ('groupe', 'Groupe')], default='individuel', max_length=20)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tuteur', models.ForeignKey(limit_choices_to={'role__in': ['tuteur', 'enseignant']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeTutorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('capacite_max', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_crees', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='tutorat.offretutorat')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('lien_visio', models.URLField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='planifiee', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_etudiant', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorat.groupetutorat')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorat.offretutorat')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_tuteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='tutorat.groupetutorat')),
            ],
            options={
                'unique_together': {('etudiant', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tutorat.seance')),
            ],
            options={
                'unique_together': {('seance', 'auteur', 'cible')},
            },
        ),
    ]
