# Generated by Django 6.0.2 on 2026-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offretutorat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='offretutorat',
            name='matiere',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='offretutorat',
            name='niveau',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_heure_debut',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], db_index=True, default='planifiee', max_length=20),
        ),
    ]
