# Generated by Django 6.0.2 on 2026-03-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0003_alter_disponibilite_options_alter_evaluation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offretutorat',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offretutorat',
            name='dates_exclues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offretutorat',
            name='mode_planning',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('auto_dispos', 'Basé sur disponibilités'), ('repetitif', 'Répétitif')], default='manuel', max_length=25),
        ),
        migrations.AddField(
            model_name='offretutorat',
            name='repetition_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offretutorat',
            name='statut_workflow',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_validation', 'En attente de validation'), ('publie', 'Publié'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='brouillon', max_length=25),
        ),
    ]
