# Generated by Django 6.0.2 on 2026-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0004_offretutorat_date_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offretutorat',
            name='matiere',
            field=models.CharField(choices=[('genie_electrique', 'Génie électrique'), ('genie_mecanique', 'Génie mécanique'), ('genie_energetique', 'Génie énergétique'), ('electrotechnique', 'Électrotechnique'), ('automatisme', 'Automatisme et contrôle'), ('genie_informatique', 'Génie informatique'), ('developpement_web', 'Développement web et mobile'), ('reseaux_telecoms', 'Réseaux et télécommunications'), ('intelligence_artificielle', 'Intelligence artificielle'), ('base_donnees', 'Bases de données'), ('production_animale', 'Production animale'), ('sante_animale', 'Santé animale'), ('nutrition_animale', 'Nutrition animale'), ('genie_animal', 'Génie animal'), ('hygiene_alimentaire', 'Hygiène et sécurité alimentaire'), ('sciences_biomedicales', 'Sciences biomédicales'), ('pharmacie', 'Pharmacie'), ('analyses_biomedicales', 'Analyses biomédicales'), ('biochimie', 'Biochimie'), ('microbiologie', 'Microbiologie'), ('telecommunications', 'Télécommunications'), ('multimedia_audiovisuel', 'Multimédia et audiovisuel'), ('reseaux_informatiques', 'Réseaux informatiques'), ('traitement_signal', 'Traitement du signal'), ('systemes_communication', 'Systèmes de communication'), ('mathematiques_appliquees', 'Mathématiques appliquées'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('statistiques', 'Statistiques'), ('sciences_environnement', "Sciences de l'environnement"), ('energies_renouvelables', 'Énergies renouvelables'), ('photovoltaique', 'Solaire photovoltaïque'), ('eolien', 'Énergie éolienne'), ('biomasse', 'Biomasse et biocarburants'), ('bioinformatique', 'Bio-informatique'), ('genomique', 'Génomique'), ('bio_statistiques', 'Biostatistiques'), ('modelisation_biologique', 'Modélisation biologique'), ('iot', 'Internet des Objets (IoT)'), ('cybersecurite', 'Cybersécurité'), ('data_science', 'Data Science'), ('cloud_computing', 'Cloud Computing'), ('robotique', 'Robotique et automation'), ('materials_science', 'Science des matériaux'), ('geosciences', 'Géosciences'), ('agro_industrie', 'Agro-industrie'), ('gestion_projet', 'Gestion de projet'), ('entrepreneuriat', 'Entrepreneuriat')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='offretutorat',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1ère année'), ('L2', 'Licence 2ème année'), ('L3', 'Licence 3ème année'), ('M1', 'Master 1ère année'), ('M2', 'Master 2ème année')], db_index=True, max_length=50),
        ),
    ]
