# Generated by Django 6.0.2 on 2026-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0005_update_insta_matiere_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offretutorat',
            name='matiere',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
