# Generated by Django 6.0.2 on 2026-04-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0007_inscriptionseance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscriptionSeance',
        ),
    ]
