# Generated by Django 6.0.2 on 2026-06-27 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0008_delete_inscriptionseance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ressource'),
        ),
    ]
